# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "MetaLLica22"  # change this!
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
redis:
  url: redis://redis:6379/0
engines:
  - name: duckduckgo
    shortcut: dd
    disabled: false
  - name: google
    shortcut: go
    disabled: false
  - name: bing
    shortcut: bi
    disabled: false
  - name: startpage
    shortcut: sp
    disabled: false
  - name: wikidata
    disabled: true
  - name: currency
    disabled: true
  - name: files
    disabled: true
  - name: ittools
    disabled: true
  - name: units
    disabled: true
  - name: openstreetmap
    disabled: true
  - name: xpath
    disabled: true
search:
  formats:
    - html
    - json  # <-- ADD THIS LINE